// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace dotnet.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20230827105530_Added Weather Checks")]
    partial class AddedWeatherChecks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("WeatherCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WeatherChecks");

                    b.HasDiscriminator<string>("Discriminator").HasValue("WeatherCheck");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StationForecast", b =>
                {
                    b.HasBaseType("WeatherCheck");

                    b.Property<Guid>("ForecastId")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("StationForecast");
                });
#pragma warning restore 612, 618
        }
    }
}
